[package]
name = "bootycall-led"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
bootycall-log = { workspace = true }
thiserror = { workspace = true }
bootycall-core = { path = "../bootycall-core" }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[lints]
workspace = true
