[workspace]
resolver = "2"
members = [
    "crates/bootycall-core",
    "crates/bootycall-dhcp",
    "crates/bootycall-tftp",
    "crates/bootycall-extractor",
    "crates/bootycall-http",
    "crates/bootycall-oled",
    "crates/bootycall-led",
    "crates/bootycall-log",
    "crates/bootycall-rs"
]

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
notify = "8.2.0"
tracing = "0.1.44"
axum = "0.8.9"
clap = { version = "4.6.1", features = ["derive"] }
bytes = "1.12.0"
dhcproto = "0.15.0"
iso9660 = "0.1.1"
fatfs = "0.3.6"
gpt = "4.1.0"
minijinja = { version = "2.21.0", features = ["loader"] }
rust-embed = "8.11.0"
anyhow = "1.0.103"
tempfile = "3.27.0"
bootycall-log = { path = "crates/bootycall-log" }
serde_json = "1.0.150"
rand = "0.10.2"
sysinfo = "0.39.5"
libc = "0.2"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
rusttype = "0.9.3"
parking_lot = "0.12.5"
