[package]
name = "bootycall-rs"
version.workspace = true
edition = "2024"

[dependencies]
bootycall-core = { path = "../bootycall-core" }
bootycall-dhcp = { path = "../bootycall-dhcp" }
bootycall-tftp = { path = "../bootycall-tftp" }
bootycall-extractor = { path = "../bootycall-extractor" }
bootycall-http = { path = "../bootycall-http" }
bootycall-oled = { path = "../bootycall-oled" }
bootycall-led = { path = "../bootycall-led" }
tokio = { workspace = true }
bootycall-log = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
