[package]
name = "bootycall-tftp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bootycall-core = { path = "../bootycall-core" }
tokio = { workspace = true }
tokio-util = { workspace = true }
bootycall-log = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
nix = { version = "0.31.3", features = ["net", "socket", "uio"] }
socket2 = "0.6.4"

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
