[package]
name = "bootycall-oled"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
sysinfo = { workspace = true }
bootycall-core = { path = "../bootycall-core" }
bootycall-log = { workspace = true }
anyhow = { workspace = true }
libc = { workspace = true }
rusttype = { workspace = true }
gpiocdev = "0.8.0"
