[package]
name = "bootycall-dhcp"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
bootycall-core = { path = "../bootycall-core" }
tokio = { workspace = true }
parking_lot = { workspace = true }
bootycall-log = { workspace = true }
dhcproto = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
