[package]
name = "bootycall-dhcp"
version.workspace = true
edition = "2024"

[dependencies]
bootycall-core = { path = "../bootycall-core" }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
bootycall-log = { workspace = true }
dhcproto = { workspace = true }
