name: CI

on:
  pull_request:
    branches:
      - main
      - master
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr:
    name: Conventional Commit
    runs-on: ubuntu-latest
    steps:
      - id: validate_pr_title
        name: Validate Conventional Commit
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - id: checkout_repository
        name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - id: get_repository_owner
        name: Get lowercased repository owner
        run: echo "owner=${OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          OWNER: ${{ github.repository_owner }}

      - id: setup_devenv
        name: Setup Devenv
        uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-cache-name: ${{ steps.get_repository_owner.outputs.owner }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skip-push: "true"

      - id: check_version
        name: Check Version
        shell: bash -c "nix develop --impure -c bash -- {0}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: version ci

      - id: check_commit_messages
        name: Check Commit Messages
        shell: bash -c "nix develop --impure -c bash -- {0}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEFAULT_BRANCH=$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)
          git fetch origin "$DEFAULT_BRANCH" --depth=1
          convco check "origin/$DEFAULT_BRANCH..HEAD"

      - id: cache_cargo
        name: Cache Cargo
        uses: ./.github/actions/cache-cargo

      - id: run_devenv_tests
        name: Run Devenv Tests
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: devenv test

      - id: run_cargo_tests
        name: Cargo Test
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: cargo test --workspace

      - id: run_cargo_clippy
        name: Cargo Clippy
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: cargo clippy --workspace

      - id: check_flake
        name: Nix Flake Check
        shell: bash -c "nix develop --impure -c bash -- {0}"
        timeout-minutes: 60
        run: >-
          nix flake check
          --accept-flake-config
          --all-systems
          --impure
          --keep-going
          --refresh
          --verbose

      - id: check_statix
        name: Check Statix
        run: nix run nixpkgs#statix -- check
