name: Nix Flake Update

on:
  schedule:
    - cron: "0 4 * * 0" # Every Sunday at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake-lock:
    name: Update flake.lock
    runs-on: ubuntu-latest
    steps:
      - id: checkout_repository
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: update_flake_lock
        name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            nix
