name: PR Test

on:
  pull_request:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Devenv
        uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-cache-name: ${{ github.repository_owner }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skip-push: "true"

      - name: Cache Cargo
        uses: ./.github/actions/cache-cargo

      - name: Run Devenv Tests
        shell: nix develop --impure --command bash -- -e {0}
        env:
          DEVENV_ROOT: ${{ github.workspace }}
        run: devenv test

      - name: Cargo Test
        shell: nix develop --impure --command bash -- -e {0}
        env:
          DEVENV_ROOT: ${{ github.workspace }}
        run: cargo test --workspace

      - name: Nix Flake Check
        shell: nix develop --impure --command bash -- -e {0}
        env:
          DEVENV_ROOT: ${{ github.workspace }}
        run: nix flake check --all-systems --impure
