name: PR Test

on:
  pull_request:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-pr:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get lowercased repository owner
        id: repository_owner
        run: echo "owner=${OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Setup Devenv
        uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-cache-name: ${{ steps.repository_owner.outputs.owner }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skip-push: "true"

      - name: Cache Cargo
        uses: ./.github/actions/cache-cargo

      - name: Run Devenv Tests
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: devenv test

      - name: Cargo Test
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: cargo test --workspace

      - name: Cargo Clippy
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: cargo clippy --workspace

      - name: Nix Flake Check
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: nix flake check --impure --all-systems
